//As a user I want to see the information that is shown in the Case View in the different languages that are available for the system..

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/');
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/auth');
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/auth/login');
  await page.getByRole('textbox').nth(0).fill('SUPERUSER');
  await page.getByRole('textbox').nth(1).fill('SUPERUSER');
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button').nth(0).click();
  await page.getByRole('menuitem').nth(1).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('option', { name: 'Français' }).click();
  await page.getByRole('link', { name: 'Cas' }).click();
  await page.getByRole('tab', { name: 'Cas', exact: true }).click();
  await expect(page.locator('text=Cas (Simplifié)')).toHaveCount(1);
  await expect(page.locator('text="Cas"')).not.toHaveCount(0);
  await expect(page.locator('text=Mes cas')).not.toHaveCount(0);
  await expect(page.locator('text=Mes cas précédents')).not.toHaveCount(0);
  await expect(page.locator('text=Les cas de mon rôle')).not.toHaveCount(0);
  await expect(page.locator('text=Id du client principal')).not.toHaveCount(0);
  await expect(page.locator('text=résultats')).not.toHaveCount(0);
  await expect(page.locator('text=Statut')).not.toHaveCount(0);
  await expect(page.locator('text=Assigné à / Revendiqué par')).not.toHaveCount(0);
  await expect(page.locator('text=ID du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Actif')).not.toHaveCount(0);
  await expect(page.locator('text=Type de client')).not.toHaveCount(0);
  await expect(page.locator('text=Particulier')).not.toHaveCount(0);
  await expect(page.locator('text=Entreprise')).not.toHaveCount(0);
  await expect(page.locator('text=Cusy')).not.toHaveCount(0);
  await expect(page.locator('text=CORP')).not.toHaveCount(0);
  await expect(page.locator('text=SME')).not.toHaveCount(0);
  await expect(page.locator('text=Origine')).not.toHaveCount(0);
  await expect(page.locator('text=SironAML')).not.toHaveCount(0);
  await expect(page.locator('text=Classifications')).not.toHaveCount(0);
  await expect(page.locator('text=Type de cas')).not.toHaveCount(0);
  await expect(page.locator('text=Alerte AML - Personne physique')).not.toHaveCount(0);
  await expect(page.locator('text=Date de création')).not.toHaveCount(0);
  await expect(page.locator('text=La semaine dernière')).not.toHaveCount(0);
  await expect(page.locator('text=Le mois dernier')).not.toHaveCount(0);
  await expect(page.locator('text=L\'année dernière')).not.toHaveCount(0);
  await expect(page.locator('text=Depuis')).not.toHaveCount(0);
  await expect(page.locator('text=Jusqu\'à')).not.toHaveCount(0);
  await expect(page.locator('text=Id du Hit')).not.toHaveCount(0);
  await expect(page.locator('text=Noms des scénarios')).not.toHaveCount(0);
  await expect(page.locator('text=Qualification du statut de la tâche')).not.toHaveCount(0);
  await expect(page.locator('text=Noms des scénarios')).not.toHaveCount(0);
  await page.locator('[data-test-id="virtuoso-top-item-list"]').getByRole('button').click();
  await expect(page.locator('text=Type de cas')).not.toHaveCount(0);
  await expect(page.locator('text=Statut du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Id du client principal')).not.toHaveCount(0);
  await expect(page.locator('text=Origine')).not.toHaveCount(0);
  await expect(page.locator('text=Type de client')).not.toHaveCount(0);
  await expect(page.locator('text=Nom')).not.toHaveCount(0);
  await expect(page.locator('text=Date de création du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Temps écoulé')).not.toHaveCount(0); 
  await expect(page.locator('text=Noms des scénarios')).not.toHaveCount(0);
  await expect(page.locator('text=Qualification du statut de la tâche')).not.toHaveCount(0);
  await expect(page.locator('text=Id du Hit')).not.toHaveCount(0);
  await expect(page.locator('text=Réinitialiser')).not.toHaveCount(0);
  await expect(page.locator('text=Fermer')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Fermer' }).click();
  await expect(page.locator('text=Type de cas')).not.toHaveCount(0);
  await expect(page.locator('text=Statut du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Id du client principal')).not.toHaveCount(0);
  await expect(page.locator('text=Origine')).not.toHaveCount(0);
  await expect(page.locator('text=Type de client')).not.toHaveCount(0);
  await expect(page.locator('text=Nom')).not.toHaveCount(0);
  await expect(page.locator('text=Date de création du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Temps écoulé')).not.toHaveCount(0);  
  await expect(page.locator('text=Noms des scénarios')).not.toHaveCount(0);
  await expect(page.locator('text=Qualification du statut de la tâche')).not.toHaveCount(0);
  await expect(page.locator('text=Id du Hit')).not.toHaveCount(0);
  await page.locator('.css-mslw24').first().click();
  await page.getByRole('button', { name: 'Détails Actif' }).click();
  await expect(page.locator('text=Nom du cas')).not.toHaveCount(0);
  await expect(page.locator('text=Dû le')).not.toHaveCount(0);
  await expect(page.locator('text=Activé le')).not.toHaveCount(0);
  await expect(page.locator('text=Modifiée le')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Alertes AML' }).click();
  await expect(page.locator('text=Scénarios')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Détails Actif' }).click();
  await page.getByRole('button', { name: 'Alertes AML' }).click();
  await page.getByRole('button', { name: 'Classifications' }).click();
  await page.getByRole('button', { name: 'Ajouter une classification' }).click();
  await page.getByRole('heading', { name: 'Ajouter une classification' }).click();
  await page.getByRole('button', { name: 'Annuler' }).click();
  await page.getByRole('button', { name: 'Ajouter une classification' }).click();
  await page.getByRole('button', { name: 'Annuler' }).click();
  await page.getByRole('tab', { name: 'Customer' }).click();
  await page.getByRole('button', { name: 'Transactions liées' }).click();
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.getByRole('button', { name: 'Document' }).click();
  await page.getByRole('button', { name: 'Créer un nouveau cas' }).click();
  await page.getByRole('button', { name: 'Annuler' }).click();
  await page.getByRole('button').nth(0).click();
  await page.getByRole('menuitem').nth(1).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('option', { name: 'Deutsch' }).click();
  await page.getByRole('link', { name: 'Cases' }).click();
  await page.getByRole('tab', { name: 'Cases', exact: true }).click();
  await page.getByRole('button', { name: 'Neuer Case erstellen' }).click();
  await page.getByRole('button', { name: 'Abbrechen' }).click();
  await expect(page.locator('text=Ergebnisse')).not.toHaveCount(0);
  await expect(page.locator('text=Zurücksetzen')).not.toHaveCount(0);
  await page.getByRole('tab', { name: 'Case', exact: true }).click();
  await page.getByRole('button', { name: 'Einzelheit Aktiv' }).click();
  await expect(page.locator('text=Case Name')).not.toHaveCount(0);
  await expect(page.locator('text=Fällig am')).not.toHaveCount(0);
  await expect(page.locator('text=Aktiviert am')).not.toHaveCount(0);
  await expect(page.locator('text=Modifiziert am')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Einzelheit Aktiv' }).click();
  await page.getByRole('button', { name: 'Zeitleiste' }).click();
  await expect(page.locator('text=Aufgabe erstellt')).not.toHaveCount(0);
  await expect(page.locator('text=Fall aktiviert')).not.toHaveCount(0);
  await expect(page.locator('text=Heute')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Zeitleiste' }).click();
  await expect(page.locator('text=Klassifikationen')).not.toHaveCount(0);
  await page.getByRole('tab', { name: 'Customer' }).click();
  await page.getByRole('button', { name: 'Transaktion Details' }).click();
  await page.getByRole('button', { name: 'Transaktion Details' }).click();
  await page.getByRole('button', { name: 'Verwandte Cases' }).click();
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.getByRole('button', { name: 'Dokument' }).click();
  await page.getByRole('button', { name: 'Dokument' }).click();
  await page.locator('[data-test-id="virtuoso-top-item-list"]').getByRole('button').nth(1).click();
  await expect(page.locator('text=Wählen Sie die anzuzeigenden Spalten aus')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Zurücksetzen' }).click();
  await page.getByRole('button', { name: 'Schliessen' }).click();
  await page.getByRole('button').nth(0).click();
  await page.getByRole('menuitem').nth(1).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('option', { name: 'Italiano' }).click();
  await page.getByRole('link', { name: 'Casi' }).click();
  await page.getByRole('tab', { name: 'Cases', exact: true }).click();
  await page.getByRole('button', { name: 'Crea nuovo caso' }).click();
  await page.getByRole('button', { name: 'Annulla' }).click();
  await expect(page.locator('text=risultati')).not.toHaveCount(0);
  await expect(page.locator('text=Reimpostare')).not.toHaveCount(0);
  await page.getByRole('tab', { name: 'Case', exact: true }).click();
  await page.getByRole('button', { name: 'Dettagli' }).click();
  await expect(page.locator('text=Nome del caso')).not.toHaveCount(0);
  await expect(page.locator('text=Dovuto il')).not.toHaveCount(0);
  await expect(page.locator('text=Attivato il')).not.toHaveCount(0);
  await expect(page.locator('text=Modificato il')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Dettagli' }).click();
  await page.getByRole('button', { name: 'Avvisi AML' }).click();
  await expect(page.locator('text=Punteggio totale')).not.toHaveCount(0);
  await expect(page.locator('text=Scenari')).not.toHaveCount(0);
  await expect(page.locator('text=Monitoraggio stretto')).not.toHaveCount(0);
  await expect(page.locator('text=Visualizza dettagli')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Avvisi AML' }).click();
  await page.getByRole('button', { name: 'Sequenza temporale' }).click();
  await expect(page.locator('text=Oggi')).not.toHaveCount(0);
  await expect(page.locator('text=Compito creato')).not.toHaveCount(0);
  await expect(page.locator('text=Caso attivato')).not.toHaveCount(0);
  await expect(page.locator('text=Aggiungi commento')).not.toHaveCount(0);
  await expect(page.locator('text=Esporta')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Sequenza temporale' }).click();
  await expect(page.locator('text=Classificazioni')).not.toHaveCount(0);
  await page.getByRole('tab', { name: 'Customer' }).click();
  await page.getByRole('button', { name: 'Dettagli della transazione' }).click();
  await page.getByRole('button', { name: 'Casi correlati' }).click();
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.getByRole('button', { name: 'Documenti' }).click();
  await page.getByRole('button', { name: 'Documenti' }).click();
  await page.locator('[data-test-id="virtuoso-top-item-list"]').getByRole('button').nth(1).click();
  await expect(page.locator('text=Seleziona le colonne da visualizzare')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Ripristina' }).click();
  await page.getByRole('button', { name: 'Chiudi' }).click();
});