//Tab details visible in risk.

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/auth/login');
  await page.getByRole('textbox').nth(0).fill('SUPERUSER');
  await page.getByRole('textbox').nth(1).fill('SUPERUSER');
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button').nth(0).click();
  await page.getByRole('menuitem').nth(1).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('option').nth(1).click();
  await page.getByRole('link').nth(0).click();
  await page.getByRole('button', { name: 'New case' }).click();
  await page.getByRole('button', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Manual Risk Level Change' }).click();
  await page.getByText('NaturalPerson').click();
  await page.getByPlaceholder('Search...').click();
  await page.getByPlaceholder('Search...').fill('678');
  await page.getByRole('option', { name: 'BusinessId: CEMT-1388678' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Open task' }).click();
  await page.locator('.css-mslw24').first().dblclick();
  await page.getByRole('button', { name: 'Open', exact: true }).click();
  await page.getByRole('option', { name: 'Low' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'New case' }).click();
  await page.getByRole('button', { name: 'Open' }).click();
  await page.getByRole('option', { name: 'Manual Risk Level Change' }).click();
  await page.getByText('NaturalPerson').click();
  await page.getByPlaceholder('Search...').click();
  await page.getByPlaceholder('Search...').fill('678');
  await page.getByRole('option', { name: 'BusinessId: CEMT-1388678' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Open task' }).click();
  await page.locator('.css-mslw24').first().dblclick();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('button', { name: 'Open', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Clients' }).click();
  await page.getByRole('button', { name: 'New client group' }).click();
  await page.getByLabel('Tenant *').click();
  await page.getByRole('option', { name: 'CENL' }).click();
  await page.getByLabel('Name *').click();
  await page.getByLabel('Name *').fill('Automation testing');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Add client' }).click();
  await page.getByPlaceholder('Search for a client...').fill('678');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.locator('td:nth-child(7)').click();
  await page.getByLabel('Audit message').fill('add');
  await page.getByRole('button', { name: 'Add client to group' }).click();
  await page.getByRole('tab', { name: 'Risk' }).click();
  await expect(page.locator('div').filter({ hasText: 'ClientRisk levelRisk scoreSKYNET CORP' }).first()).toHaveCount(1);
  await expect(page.getByText('SKYNET CORP')).not.toHaveCount(0);
  await expect(page.getByText('Risk')).not.toHaveCount(0);
  await expect(page.getByText('Calculated risk level')).not.toHaveCount(0);
  await expect(page.getByText('Calculated risk score')).not.toHaveCount(0);
  await expect(page.getByText('Calculation date')).not.toHaveCount(0);
  await expect(page.getByText('Risk level')).not.toHaveCount(0);
  await expect(page.getByText('Risk score')).not.toHaveCount(0);
});