import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8181/');
  await page.getByLabel('User name').fill('SUPERUSER');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('SUPERUSER');
  await page.getByRole('button', { name: 'Log on' }).click();
  await page.getByRole('link', { name: 'Cases' }).click();
  await page.locator('input[name="case\\.payload\\.mainClientId"]').click();
  await page.locator('input[name="case\\.payload\\.mainClientId"]').fill('C-133');
  await page.locator('input[name="case\\.payload\\.mainClientId"]').press('Enter');
  await page.locator('input[name="case\\.presentableValue"]').click();
  await page.locator('input[name="case\\.presentableValue"]').fill('C-133');
  await page.locator('input[name="case\\.presentableValue"]').press('Enter');
  await page.getByRole('button', { name: 'Reset filter' }).first().click();
  await page.getByTestId('virtuoso-item-list').getByText('Onboarding').click();
  await page.getByText('C-133OnboardingActive').dblclick();
  await page.getByTestId('virtuoso-item-list').getByText('Data Capture').click();
  await page.getByText('HT-135Data CaptureRelationship ManagerOpenSUPERUSER14/08/2024').dblclick();
  await page.getByRole('main').getByRole('button').click();
  await page.getByLabel('Account Number *').click();
  await page.getByLabel('Account Number *').fill('123');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('li').filter({ hasText: '123 ()' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Account Details').click();
  await page.getByLabel('Advisory Location *').click();
  await page.getByRole('option', { name: 'Singapore' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByTestId('virtuoso-item-list').getByText('Account Review').click();
  await page.getByText('HT-136Account ReviewOperationsOpen14/08/2024').click();
  await page.getByTitle('open').dblclick();
  await page.getByText('Additional Questions').click();
  await page.getByLabel('Is Suspicious Account? *').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByText('Account Details').click();
  await page.getByText('Address').click();
  await page.getByRole('main').getByRole('button').click();
  await page.getByLabel('Street').click();
  await page.getByLabel('Street').fill('Hello');
  await page.getByLabel('Postal Code').click();
  await page.getByLabel('Postal Code').fill('123');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Complete' }).click();
});