import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8181/');
  await page.goto('http://localhost:8181/auth');
  await page.goto('http://localhost:8181/auth/login');
  await page.getByLabel('Username').fill('SUPERUSER');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('SUPERUSER');
  await page.getByRole('button', { name: 'Log on' }).click();
  await page.getByRole('button', { name: 'Create...' }).click();
  await page.getByText('New case').click();
  await page.getByLabel('Open').click();
  await page.getByRole('option', { name: 'Onboarding Case' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.locator('[data-test-id="virtuoso-item-list"]').getByText('Data Capture').click();
  await page.locator('[data-test-id="virtuoso-item-list"]').getByText('Data Capture').dblclick();
  await page.getByText('Natural Person').click();
  await page.locator('section').filter({ hasText: /^Natural Person$/ }).getByRole('button').click();
  await page.getByLabel('Full Name').click();
  await page.getByLabel('Full Name').fill('Testing');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('span').filter({ hasText: 'Natural Person' }).click();
  await page.getByText('None').click();
  await page.getByRole('option', { name: 'All' }).click();
  await page.locator('div').filter({ hasText: /^Full NameFull Name$/ }).nth(2).click();
  await page.locator('li').filter({ hasText: '(unnamed entry)' }).getByRole('button').click();
  await page.getByText('Natural Person Details').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('li').filter({ hasText: 'Natural Person Details' }).locator('div').nth(2).click();
  await page.locator('._widgetWrapper_xe2sy_1 > .MuiButtonBase-root').first().click();
  await page.getByLabel('Comment', { exact: true }).fill('testing');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('._widgetWrapper_xe2sy_1 > .MuiButtonBase-root').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('All').click();
  await page.getByRole('option', { name: 'All' }).click();
  await page.getByLabel('Data history').getByRole('img').first().click();
  await page.goto('http://localhost:8181/task-manager/task/aHVtYW50YXNrOi8vaHVtYW50YXNrcy8wNzYwNjU4Ny05Mjg1LTRkY2QtYTc1My1mOGI0YmFjOTgxMDI');
  await page.goto('http://localhost:8181/auth');
  await page.goto('http://localhost:8181/task-manager/task/aHVtYW50YXNrOi8vaHVtYW50YXNrcy8wNzYwNjU4Ny05Mjg1LTRkY2QtYTc1My1mOGI0YmFjOTgxMDI');
  await page.locator('ul').getByRole('button').click();
  await page.locator('li').filter({ hasText: '(unnamed entry)' }).getByRole('button').click();
  await page.locator('div').filter({ hasText: /^Natural Person Details$/ }).locator('div').click();
});