//As a user I want that the User Settings are displayed in the language that I have chosen for the application.

import { test, expect } from '@playwright/test';

test('user language settings', async ({ page }) => {
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/');
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/auth');
  await page.goto('http://ccm-ci-develop.imtf-devops.com:8181/auth/login');
  await page.getByRole('textbox', { name: 'username' }).fill('SUPERUSER');
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('SUPERUSER');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('button', { name: 'SS' }).click();
  await page.getByRole('menuitem', { name: 'Settings' }).click();
  await expect(page.locator('text=User settings')).toHaveCount(2);
  await expect(page.locator('text=Language')).toHaveCount(1);
  await expect(page.locator('text=First name')).toHaveCount(1);
  await expect(page.locator('text=Last name')).toHaveCount(1);
  await expect(page.locator('text=Groups')).toHaveCount(1);
  await expect(page.locator('text="Application settings"')).toHaveCount(1);
  await expect(page.locator('text=Appearance')).toHaveCount(1);
  await expect(page.locator('text=Dossier default view')).toHaveCount(1);
  await expect(page.locator('text=Clear application settings')).toHaveCount(1);
  await expect(page.locator('text=Auto')).toHaveCount(1);
  await expect(page.locator('text="Search"')).toHaveCount(1);
  await expect(page.locator('text=Browser persisted data (saved search, theme, folders and search view layout, etc')).toHaveCount(1);
  await page.getByRole('button', { name: 'English (US)' }).click();
  await page.getByRole('option', { name: 'English (GB)' }).click();
  await expect(page.locator('text=User settings')).toHaveCount(2);
  await expect(page.locator('text=Language')).toHaveCount(1);
  await expect(page.locator('text=First name')).toHaveCount(1);
  await expect(page.locator('text=Last name')).toHaveCount(1);
  await expect(page.locator('text=Groups')).toHaveCount(1);
  await expect(page.locator('text="Application settings"')).toHaveCount(1);
  await expect(page.locator('text=Appearance')).toHaveCount(1);
  await expect(page.locator('text=Dossier default view')).toHaveCount(1);
  await expect(page.locator('text=Clear application settings')).toHaveCount(1);
  await expect(page.locator('text=Auto')).toHaveCount(1);
  await expect(page.locator('text="Search"')).toHaveCount(1);
  await expect(page.locator('text=Browser persisted data (saved search, theme, folders and search view layout, etc')).toHaveCount(1);
  await page.getByRole('button', { name: 'English (GB)' }).click();
  await page.getByRole('option', { name: 'Deutsch' }).click();
  await expect(page.locator('text=Benutzereinstellungen')).toHaveCount(2);
  await expect(page.locator('text=Sprache')).toHaveCount(1);
  await expect(page.locator('text=Vorname')).toHaveCount(1);
  await expect(page.locator('text=Nachname')).toHaveCount(1);
  await expect(page.locator('text=Gruppen')).toHaveCount(1);
  await expect(page.locator('text="Einstellungen"')).toHaveCount(1);
  await expect(page.locator('text=Darstellung')).toHaveCount(1);
  await expect(page.locator('text=Dossier-Standardansicht')).toHaveCount(1);
  await expect(page.locator('text=Einstellungen löschen')).toHaveCount(1);
  await expect(page.locator('text=Automatisch')).toHaveCount(1);
  await expect(page.locator('text="Suche"')).toHaveCount(1);
  await expect(page.locator('text=Persistierte Daten (gespeicherte Suche, Thema, Ordner und Layout der Suchansicht')).toHaveCount(1);
  await page.getByRole('button', { name: 'Deutsch' }).click();
  await page.getByRole('option', { name: 'Français' }).click();
  await expect(page.locator('text=Paramètres utilisateur')).toHaveCount(2);
  await expect(page.locator('text=Changer de langue')).toHaveCount(1);
  await expect(page.locator('text=Prénom')).toHaveCount(1);
  await expect(page.locator('text="Nom"')).toHaveCount(1);
  await expect(page.locator('text=Groupes')).toHaveCount(1);
  await expect(page.locator('text="Paramètres de l\'application"')).toHaveCount(1);
  await expect(page.locator('text="Apparence"')).toHaveCount(1);
  await expect(page.locator('text=Vue par défaut des dossiers')).toHaveCount(1);
  await expect(page.locator('text=Supprimer les paramètres de l\'application')).toHaveCount(1);
  await expect(page.locator('text=Auto')).toHaveCount(1);
  await expect(page.locator('text="Recherche"')).toHaveCount(1);
  await expect(page.locator('text=Données persistantes du navigateur (recherche sauvegardée, apparence, dossiers e')).toHaveCount(1);
  await page.getByRole('button', { name: 'Français' }).click();
  await page.getByRole('option', { name: 'Italiano' }).click();
  await expect(page.locator('text=Impostazioni utente')).toHaveCount(2);
  await expect(page.locator('text=Linguaggio')).toHaveCount(1);
  await expect(page.locator('text="Nome"')).toHaveCount(1);
  await expect(page.locator('text=Cognome')).toHaveCount(1);
  await expect(page.locator('text=Gruppi')).toHaveCount(1);
  await expect(page.locator('text="Impostazioni dell\'applicazione"')).toHaveCount(1);
  await expect(page.locator('text=Aspetto')).toHaveCount(1);
  await expect(page.locator('text=Visualizzazione del dossier predefinita')).toHaveCount(1);
  await expect(page.locator('text=Cancella impostazioni dell\'applicazione')).toHaveCount(1);
  await expect(page.locator('text=Auto')).toHaveCount(1);
  await expect(page.locator('text="Ricerca"')).toHaveCount(1);
  await expect(page.locator('text=Dati persistenti del browser (ricerca salvata, tema, cartelle e layout di visual')).toHaveCount(1);
});