import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8181/auth/login');
  await page.getByLabel('username').fill('SUPERUSER');
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('SUPERUSER');
  await page.getByRole('button', { name: 'Log on' }).click();
  await page.getByRole('button', { name: 'Create...' }).click();
  await page.getByText('New case').click();
  await page.getByLabel('Open').click();
  await page.getByRole('option', { name: 'Onboarding Case' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.locator('[data-test-id="virtuoso-item-list"]').getByText('Data Capture').click();
  await page.getByText('HT-19Data CaptureOpen07/12/2023').dblclick();
  await page.locator('li').filter({ hasText: 'Natural Person' }).locator('div').nth(2).click();
  await page.locator('section').filter({ hasText: /^Natural Person$/ }).getByRole('button').click();
  await page.getByLabel('Full Name').click();
  await page.getByLabel('Full Name').fill('Automation');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('li').filter({ hasText: 'Account' }).locator('div').nth(2).click();
  await page.locator('li').filter({ hasText: 'Natural Person' }).locator('div').nth(2).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('li').filter({ hasText: 'Account' }).locator('div').nth(2).click();
  await page.locator('section').filter({ hasText: /^Account$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Cases' }).first().click();
  await page.getByText('Onboarding').nth(2).click();
  await page.getByText('C-19OnboardingActive').dblclick();
  await page.locator('[data-test-id="virtuoso-item-list"]').getByText('Data Capture').click();
  await page.getByText('HT-19Data CaptureOpen07/12/2023').dblclick();
  await page.locator('li').filter({ hasText: 'Natural Person' }).locator('div').nth(2).click();
  await page.locator('li').filter({ hasText: '(unnamed entry)' }).locator('div').nth(2).click();
  await page.getByLabel('First Name *').click();
  await page.getByLabel('First Name *').fill('Automation');
  await page.getByLabel('Last Name *').click();
  await page.getByLabel('Last Name *').fill('testing');
  await page.getByLabel('Male', { exact: true }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('tab', { name: 'Customer' }).click();
  await page.getByRole('button', { name: 'Clients' }).nth(1).click();
  await expect(page.getByRole('heading', { name: 'VIEW MORE' })).toHaveCount(0);
});